---
# tasks file for sec-rhel-prod
    - name: enable service firewall 
      service: 
          name: "{{ item }}"
          status: started
          enable: yes   
      loop:
          - firewalld     

    - name: Enable SELinux
      selinux:
        policy: targeted
        state: enforcing

    - name: desabilitar servico de producao 
      service: 
          name: "{{ item }}"
          status: stopped
          enable: no   
      loop:
          - postfix
          - nfs
          - smbd
      ignore_errors: 
      register: _result

    - name: Debug 
      debug: 
        msg: 
        - Saida dos servicos desabilitados  '{{ _result }}' 
        